apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: istio-system
spec:
  secretName: prometheus-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - teokyllc
  commonName: prometheus.teokyllc.internal
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - prometheus.teokyllc.internal
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: monitoring
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-grafana
      protocol: HTTPS
    hosts:
    - prometheus.teokyllc.internal
    tls:
      mode: SIMPLE
      credentialName: prometheus-tls
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: monitoring
spec:
  hosts:
  - prometheus.teokyllc.internal
  gateways:
  - prometheus-gateway
  http:
  - route:
    - destination:
        host: prometheus-k8s
        port:
          number: 9090
